version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: vaultline_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: vaultline
      POSTGRES_PASSWORD: vaultline
      POSTGRES_DB: vaultline
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
